version: 2

jobs:
  build:
    filters:
      branches:
        only: master
    docker:
      - image: peavers/docker-firebase-ember:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing Libraries
          command: npm install

      - run:
          name: Building Ember App
          command: ember build --prod

      - run:
          name: Deploying to Firebase
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --project $FIREBASE_DEPLOY_PROJECT --non-interactive
