version: 2

jobs:
  build:
    filters:
      branches:
        only: master
    docker:
      - image: peavers/docker-firebase-ember:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Installing Libraries
          command: npm install
      - save_cache:
          paths:
            - ~/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Building Ember App
          command: ember build --prod

      - run:
          name: Deploying to Firebase
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --project $FIREBASE_DEPLOY_PROJECT --non-interactive
